# Generated by Django 6.0.6 on 2026-06-16 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutputSanitization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_type', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown'), ('code', 'Generated Code'), ('text', 'Plain Text'), ('json', 'JSON'), ('xml', 'XML'), ('sql', 'SQL Query'), ('shell', 'Shell Command'), ('javascript', 'JavaScript'), ('python', 'Python'), ('yaml', 'YAML')], max_length=50)),
                ('is_sanitized', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('safe', 'Safe')], default='safe', max_length=20)),
                ('raw_output', models.TextField(blank=True)),
                ('sanitized_output', models.TextField(blank=True)),
                ('vulnerabilities_found', models.JSONField(blank=True, default=list)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Output Sanitization',
                'verbose_name_plural': 'Output Sanitizations',
                'db_table': 'output_handling_sanitization',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnsafeCodeFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('sql', 'SQL'), ('bash', 'Bash/Shell'), ('powershell', 'PowerShell'), ('java', 'Java'), ('csharp', 'C#'), ('rust', 'Rust'), ('go', 'Go')], max_length=50)),
                ('vulnerability_type', models.CharField(choices=[('sql_injection', 'SQL Injection'), ('command_injection', 'Command Injection'), ('path_traversal', 'Path Traversal'), ('insecure_deserialization', 'Insecure Deserialization'), ('hardcoded_credentials', 'Hardcoded Credentials'), ('insecure_crypto', 'Insecure Cryptography'), ('buffer_overflow', 'Buffer Overflow'), ('open_redirect', 'Open Redirect'), ('insecure_file_upload', 'Insecure File Upload'), ('other', 'Other')], max_length=50)),
                ('code_snippet', models.TextField(blank=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('safe', 'Safe')], max_length=20)),
                ('mitigation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unsafe Code Finding',
                'verbose_name_plural': 'Unsafe Code Findings',
                'db_table': 'output_handling_unsafe_code',
            },
        ),
        migrations.CreateModel(
            name='XSSFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xss_type', models.CharField(choices=[('stored', 'Stored XSS'), ('reflected', 'Reflected XSS'), ('dom_based', 'DOM-based XSS'), ('mutation', 'Mutation XSS')], max_length=50)),
                ('payload_preview', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('safe', 'Safe')], max_length=20)),
                ('context', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'XSS Finding',
                'verbose_name_plural': 'XSS Findings',
                'db_table': 'output_handling_xss_finding',
            },
        ),
    ]
