# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('output_handling', '0001_initial'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputsanitization',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_sanitizations', to='scans.aiscan'),
        ),
        migrations.AddField(
            model_name='unsafecodefinding',
            name='sanitization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsafe_code_findings', to='output_handling.outputsanitization'),
        ),
        migrations.AddField(
            model_name='xssfinding',
            name='sanitization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xss_findings', to='output_handling.outputsanitization'),
        ),
    ]
