# Generated by Django 6.0.6 on 2026-06-16 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptExposureTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('direct_request', 'Direct Prompt Request'), ('role_play', 'Role Play Scenario'), ('token_guess', 'Token Guessing'), ('error_induction', 'Error Induction'), ('format_manipulation', 'Format Manipulation'), ('encoding_bypass', 'Encoding Bypass'), ('language_switch', 'Language Switch')], max_length=50)),
                ('test_input', models.TextField()),
                ('test_output', models.TextField(blank=True)),
                ('is_successful', models.BooleanField(default=False, help_text='Successfully extracted information')),
                ('exposed_content', models.TextField(blank=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prompt Exposure Test',
                'verbose_name_plural': 'Prompt Exposure Tests',
                'db_table': 'prompt_leakage_exposure_test',
            },
        ),
        migrations.CreateModel(
            name='PromptLeakageScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_prompt_hash', models.CharField(blank=True, max_length=255)),
                ('leakage_found', models.BooleanField(default=False)),
                ('leaked_content', models.TextField(blank=True)),
                ('exposure_type', models.CharField(blank=True, choices=[('extraction', 'Direct Extraction'), ('inference', 'Inferred via Responses'), ('error_message', 'Error Message Exposure'), ('debug_output', 'Debug Output'), ('log_exposure', 'Log File Exposure'), ('api_exposure', 'API Response Exposure'), ('side_channel', 'Side Channel Leakage'), ('none', 'No Leakage Detected')], max_length=50)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('prompt_hardening_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prompt Leakage Scan',
                'verbose_name_plural': 'Prompt Leakage Scans',
                'db_table': 'prompt_leakage_scan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretInPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_type', models.CharField(choices=[('api_key', 'API Key'), ('password', 'Password'), ('token', 'Token'), ('database_url', 'Database URL'), ('endpoint', 'Internal Endpoint'), ('credential', 'Credential'), ('pii', 'PII'), ('internal_info', 'Internal Information')], max_length=50)),
                ('location', models.CharField(help_text='Location within the prompt', max_length=255)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Secret in Prompt',
                'verbose_name_plural': 'Secrets in Prompts',
                'db_table': 'prompt_leakage_secret',
            },
        ),
    ]
