# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompt_leakage', '0001_initial'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptleakagescan',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_leakage_scans', to='scans.aiscan'),
        ),
        migrations.AddField(
            model_name='promptexposuretest',
            name='leakage_scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure_tests', to='prompt_leakage.promptleakagescan'),
        ),
        migrations.AddField(
            model_name='secretinprompt',
            name='leakage_scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets_found', to='prompt_leakage.promptleakagescan'),
        ),
    ]
