# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        ('projects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Finding Note',
                'verbose_name_plural': 'Finding Notes',
                'db_table': 'findings_finding_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FindingTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('module_type', models.CharField(choices=[('llm01', 'LLM01 - Prompt Injection'), ('llm02', 'LLM02 - Sensitive Information Disclosure'), ('llm03', 'LLM03 - Supply Chain Security'), ('llm04', 'LLM04 - Data and Model Poisoning'), ('llm05', 'LLM05 - Improper Output Handling'), ('llm06', 'LLM06 - Excessive Agency'), ('llm07', 'LLM07 - System Prompt Leakage'), ('llm08', 'LLM08 - Vector and Embedding Security'), ('llm09', 'LLM09 - Misinformation and Hallucination'), ('llm10', 'LLM10 - Unbounded Consumption')], max_length=50)),
                ('total_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('avg_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Finding Trend',
                'verbose_name_plural': 'Finding Trends',
                'db_table': 'findings_finding_trend',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_type', models.CharField(choices=[('llm01', 'LLM01 - Prompt Injection'), ('llm02', 'LLM02 - Sensitive Information Disclosure'), ('llm03', 'LLM03 - Supply Chain Security'), ('llm04', 'LLM04 - Data and Model Poisoning'), ('llm05', 'LLM05 - Improper Output Handling'), ('llm06', 'LLM06 - Excessive Agency'), ('llm07', 'LLM07 - System Prompt Leakage'), ('llm08', 'LLM08 - Vector and Embedding Security'), ('llm09', 'LLM09 - Misinformation and Hallucination'), ('llm10', 'LLM10 - Unbounded Consumption')], max_length=50)),
                ('finding_type', models.CharField(help_text='Specific finding type within the module', max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('owasp_category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('accepted_risk', 'Accepted Risk')], default='open', max_length=50)),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Module-specific evidence/context')),
                ('remediation', models.TextField(blank=True, help_text='Remediation steps')),
                ('references', models.JSONField(blank=True, default=list, help_text='External references/links')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_findings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='projects.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finding',
                'verbose_name_plural': 'Findings',
                'db_table': 'findings_finding',
                'ordering': ['-discovered_at'],
            },
        ),
    ]
