# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('findings', '0001_initial'),
        ('organizations', '__first__'),
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='scans.aiscan'),
        ),
        migrations.AddField(
            model_name='findingnote',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='findings.finding'),
        ),
        migrations.AddField(
            model_name='findingnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='findingtrend',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_trends', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['organization', 'module_type', 'severity'], name='findings_fi_organiz_fcaabe_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['organization', 'status'], name='findings_fi_organiz_32eab9_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['scan'], name='findings_fi_scan_id_ab138e_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['risk_score'], name='findings_fi_risk_sc_d5663c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='findingtrend',
            unique_together={('organization', 'date', 'module_type')},
        ),
    ]
