# Generated by Django 6.0.6 on 2026-06-16 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetIntegrityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('hash', 'Hash Verification'), ('checksum', 'Checksum'), ('statistical', 'Statistical Analysis'), ('provenance', 'Provenance Check'), ('poisoning', 'Poisoning Detection')], max_length=50)),
                ('is_passed', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dataset Integrity Check',
                'verbose_name_plural': 'Dataset Integrity Checks',
                'db_table': 'data_poisoning_integrity',
            },
        ),
        migrations.CreateModel(
            name='RAGDocumentValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.CharField(help_text='Document identifier in RAG system', max_length=255)),
                ('document_name', models.CharField(max_length=255)),
                ('content_hash', models.CharField(blank=True, max_length=255)),
                ('is_poisoned', models.BooleanField(default=False)),
                ('poisoning_indicators', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RAG Document Validation',
                'verbose_name_plural': 'RAG Document Validations',
                'db_table': 'data_poisoning_rag_document',
            },
        ),
        migrations.CreateModel(
            name='TrainingDataValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_source', models.CharField(choices=[('training', 'Training Data'), ('fine_tuning', 'Fine-Tuning Data'), ('rag_document', 'RAG Document'), ('embedding', 'Embedding Source'), ('validation', 'Validation Set'), ('custom', 'Custom')], max_length=50)),
                ('data_fingerprint', models.CharField(blank=True, help_text='Hash/fingerprint of dataset', max_length=255)),
                ('integrity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('anomalies_detected', models.JSONField(blank=True, default=list)),
                ('tampering_indicators', models.JSONField(blank=True, default=list)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('validation_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning'), ('not_tested', 'Not Tested')], default='not_tested', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Training Data Validation',
                'verbose_name_plural': 'Training Data Validations',
                'db_table': 'data_poisoning_validation',
                'ordering': ['-created_at'],
            },
        ),
    ]
