# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_poisoning', '0001_initial'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdatavalidation',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_validations', to='scans.aiscan'),
        ),
        migrations.AddField(
            model_name='ragdocumentvalidation',
            name='validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_validations', to='data_poisoning.trainingdatavalidation'),
        ),
        migrations.AddField(
            model_name='datasetintegritycheck',
            name='validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_checks', to='data_poisoning.trainingdatavalidation'),
        ),
    ]
