# Generated by Django 6.0.6 on 2026-06-16 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitationValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('citation_text', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_title', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('partially_verified', 'Partially Verified'), ('unverifiable', 'Unverifiable'), ('fabricated', 'Fabricated'), ('error', 'Error/Invalid')], max_length=50)),
                ('verification_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Citation Validation',
                'verbose_name_plural': 'Citation Validations',
                'db_table': 'hallucination_citation',
            },
        ),
        migrations.CreateModel(
            name='HallucinationFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_text', models.TextField(blank=True)),
                ('output_text', models.TextField()),
                ('hallucination_type', models.CharField(choices=[('factual_error', 'Factual Error'), ('unsupported_claim', 'Unsupported Claim'), ('contradiction', 'Internal Contradiction'), ('made_up_source', 'Made-up Source/Reference'), ('statistical_error', 'Statistical Error'), ('logic_error', 'Logical Error'), ('temporal_error', 'Temporal/Date Error'), ('numerical_error', 'Numerical Error'), ('confabulation', 'Confabulation'), ('other', 'Other')], max_length=50)),
                ('hallucination_score', models.DecimalField(decimal_places=2, default=0, help_text='0-100', max_digits=5)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('citations_valid', models.BooleanField(default=False)),
                ('verified_sources', models.JSONField(blank=True, default=list, help_text='Sources that verify/refute the claim')),
                ('fact_check_results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hallucination Finding',
                'verbose_name_plural': 'Hallucination Findings',
                'db_table': 'hallucination_finding',
                'ordering': ['-hallucination_score'],
            },
        ),
        migrations.CreateModel(
            name='ResponseValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_text', models.TextField()),
                ('overall_validity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('needs_review', 'Needs Review'), ('invalid', 'Invalid'), ('uncertain', 'Uncertain')], max_length=50)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Response Validation',
                'verbose_name_plural': 'Response Validations',
                'db_table': 'hallucination_response_validation',
            },
        ),
    ]
