# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hallucination', '0001_initial'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallucinationfinding',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallucination_findings', to='scans.aiscan'),
        ),
        migrations.AddField(
            model_name='citationvalidation',
            name='hallucination_finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_validations', to='hallucination.hallucinationfinding'),
        ),
        migrations.AddField(
            model_name='responsevalidation',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_validations', to='scans.aiscan'),
        ),
        migrations.AddIndex(
            model_name='hallucinationfinding',
            index=models.Index(fields=['scan', 'hallucination_type'], name='hallucinati_scan_id_73f1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='hallucinationfinding',
            index=models.Index(fields=['severity'], name='hallucinati_severit_46053a_idx'),
        ),
    ]
