# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_description', models.TextField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('expired', 'Expired')], default='pending', max_length=50)),
                ('risk_assessment', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_approvals', to='ai_assets.aiagent')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_actions', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action Approval',
                'verbose_name_plural': 'Action Approvals',
                'db_table': 'excessive_agency_action_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('file_system', 'File System'), ('database', 'Database'), ('api', 'External API'), ('internal_service', 'Internal Service'), ('code_repository', 'Code Repository'), ('cloud_resource', 'Cloud Resource'), ('user_data', 'User Data'), ('llm_model', 'LLM Model'), ('vector_db', 'Vector Database'), ('email', 'Email System'), ('slack', 'Slack'), ('custom', 'Custom')], max_length=50)),
                ('action', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('execute', 'Execute'), ('admin', 'Admin'), ('delete', 'Delete'), ('deploy', 'Deploy'), ('access_internal', 'Access Internal Systems'), ('access_external', 'Access External APIs'), ('modify_system', 'Modify System Config'), ('custom', 'Custom')], max_length=50)),
                ('is_granted', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('requires_human_approval', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_permissions', to='ai_assets.aiagent')),
            ],
            options={
                'verbose_name': 'Agent Permission',
                'verbose_name_plural': 'Agent Permissions',
                'db_table': 'excessive_agency_agent_permission',
                'ordering': ['-risk_score'],
                'unique_together': {('agent', 'permission_name')},
            },
        ),
        migrations.CreateModel(
            name='ToolAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=255)),
                ('action_performed', models.TextField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked'), ('flagged', 'Flagged'), ('pending_review', 'Pending Review')], max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_access_logs', to='ai_assets.aiagent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tool_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool Access Log',
                'verbose_name_plural': 'Tool Access Logs',
                'db_table': 'excessive_agency_tool_access_log',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['agent', 'status'], name='excessive_a_agent_i_b66e27_idx'), models.Index(fields=['risk_level'], name='excessive_a_risk_le_3f73e4_idx')],
            },
        ),
    ]
