# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_id', models.CharField(help_text='e.g., OWASP-GENAI-LLM01-01', max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('risk_category', models.CharField(blank=True, help_text='Maps to OWASP LLM category', max_length=100)),
                ('implementation_guidance', models.TextField(blank=True)),
                ('verification_method', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compliance Control',
                'verbose_name_plural': 'Compliance Controls',
                'db_table': 'compliance_control',
                'ordering': ['framework', 'control_id'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(choices=[('owasp_genai', 'OWASP GenAI Security'), ('nist_ai_rmf', 'NIST AI RMF'), ('iso_42001', 'ISO/IEC 42001'), ('iso_27001', 'ISO 27001'), ('mitre_atlas', 'MITRE ATLAS')], max_length=50, unique=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('total_controls', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compliance Framework',
                'verbose_name_plural': 'Compliance Frameworks',
                'db_table': 'compliance_framework',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping_type', models.CharField(choices=[('automated', 'Automated'), ('manual', 'Manual'), ('ai_suggested', 'AI Suggested')], default='automated', max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compliance Mapping',
                'verbose_name_plural': 'Compliance Mappings',
                'db_table': 'compliance_mapping',
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('full', 'Full Report'), ('summary', 'Executive Summary'), ('gap_analysis', 'Gap Analysis'), ('certification', 'Certification Readiness')], default='full', max_length=50)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('control_summary', models.JSONField(blank=True, default=dict)),
                ('findings_summary', models.JSONField(blank=True, default=dict)),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compliance Report',
                'verbose_name_plural': 'Compliance Reports',
                'db_table': 'compliance_report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheckResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('not_applicable', 'Not Applicable'), ('not_tested', 'Not Tested'), ('partial', 'Partially Compliant')], default='not_tested', max_length=50)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_results', to='projects.project')),
            ],
            options={
                'verbose_name': 'Compliance Check Result',
                'verbose_name_plural': 'Compliance Check Results',
                'db_table': 'compliance_check_result',
            },
        ),
    ]
