# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('findings', '0001_initial'),
        ('organizations', '__first__'),
        ('projects', '__first__'),
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecheckresult',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_results', to='scans.aiscan'),
        ),
        migrations.AddField(
            model_name='compliancecheckresult',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='compliance.compliancecontrol'),
        ),
        migrations.AddField(
            model_name='compliancecontrol',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='compliance.complianceframework'),
        ),
        migrations.AddField(
            model_name='compliancecheckresult',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='compliance.complianceframework'),
        ),
        migrations.AddField(
            model_name='compliancemapping',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_mappings', to='compliance.compliancecontrol'),
        ),
        migrations.AddField(
            model_name='compliancemapping',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_mappings', to='findings.finding'),
        ),
        migrations.AddField(
            model_name='compliancemapping',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='compliance.complianceframework'),
        ),
        migrations.AddField(
            model_name='compliancemapping',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_mappings', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='compliance.complianceframework'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reports', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancecontrol',
            unique_together={('framework', 'control_id')},
        ),
        migrations.AlterUniqueTogether(
            name='compliancecheckresult',
            unique_together={('scan', 'control')},
        ),
        migrations.AlterUniqueTogether(
            name='compliancemapping',
            unique_together={('finding', 'control')},
        ),
    ]
