# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assets', '0001_initial'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorDBSecurityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_isolation_valid', models.BooleanField(default=False)),
                ('encryption_at_rest', models.BooleanField(default=False)),
                ('encryption_in_transit', models.BooleanField(default=False)),
                ('access_control_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('security_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_assessments', to='scans.aiscan')),
                ('vector_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_assessments', to='ai_assets.vectordatabase')),
            ],
            options={
                'verbose_name': 'Vector DB Security Assessment',
                'verbose_name_plural': 'Vector DB Security Assessments',
                'db_table': 'vector_security_db_assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantIsolationCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_a_id', models.CharField(max_length=255)),
                ('tenant_b_id', models.CharField(max_length=255)),
                ('cross_tenant_access_detected', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning'), ('not_tested', 'Not Tested')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolation_checks', to='vector_security.vectordbsecurityassessment')),
            ],
            options={
                'verbose_name': 'Tenant Isolation Check',
                'verbose_name_plural': 'Tenant Isolation Checks',
                'db_table': 'vector_security_tenant_isolation',
            },
        ),
        migrations.CreateModel(
            name='RAGSecurityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retrieval_security_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('prompt_injection_risk', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('data_exposure_risk', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rag_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_assessments', to='ai_assets.ragsystem')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_assessments', to='vector_security.vectordbsecurityassessment')),
            ],
            options={
                'verbose_name': 'RAG Security Assessment',
                'verbose_name_plural': 'RAG Security Assessments',
                'db_table': 'vector_security_rag_assessment',
            },
        ),
        migrations.CreateModel(
            name='EmbeddingExposureFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_id', models.CharField(max_length=255)),
                ('sensitive_data_type', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('exposure_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_exposures', to='vector_security.vectordbsecurityassessment')),
            ],
            options={
                'verbose_name': 'Embedding Exposure Finding',
                'verbose_name_plural': 'Embedding Exposure Findings',
                'db_table': 'vector_security_embedding_exposure',
            },
        ),
    ]
