# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        ('projects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scan_type', models.CharField(choices=[('prompt_injection', 'LLM01 - Prompt Injection'), ('sensitive_info', 'LLM02 - Sensitive Information Disclosure'), ('supply_chain', 'LLM03 - Supply Chain Security'), ('data_poisoning', 'LLM04 - Data and Model Poisoning'), ('output_handling', 'LLM05 - Improper Output Handling'), ('excessive_agency', 'LLM06 - Excessive Agency'), ('prompt_leakage', 'LLM07 - System Prompt Leakage'), ('vector_security', 'LLM08 - Vector and Embedding Security'), ('hallucination', 'LLM09 - Misinformation and Hallucination'), ('unbounded_consumption', 'LLM10 - Unbounded Consumption'), ('full_assessment', 'Full Security Assessment')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('target_type', models.CharField(blank=True, choices=[('model', 'AI Model'), ('agent', 'AI Agent'), ('prompt', 'Prompt Text'), ('rag', 'RAG System'), ('vector_db', 'Vector Database'), ('dataset', 'Dataset'), ('application', 'Application'), ('custom', 'Custom')], max_length=50)),
                ('target_id', models.UUIDField(blank=True, help_text='Polymorphic target reference', null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Scan configuration parameters')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scans', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='projects.project')),
            ],
            options={
                'verbose_name': 'AI Scan',
                'verbose_name_plural': 'AI Scans',
                'db_table': 'scans_ai_scan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='scans_ai_sc_organiz_c713a1_idx'), models.Index(fields=['organization', 'scan_type'], name='scans_ai_sc_organiz_ba828c_idx'), models.Index(fields=['project'], name='scans_ai_sc_project_87a527_idx')],
            },
        ),
    ]
