# Generated by Django 5.2.15 on 2026-06-23 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiscan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='aiscan',
            name='scan_type',
            field=models.CharField(choices=[('prompt_injection', 'LLM01 - Prompt Injection'), ('sensitive_info', 'LLM02 - Sensitive Information Disclosure'), ('supply_chain', 'LLM03 - Supply Chain Security'), ('data_poisoning', 'LLM04 - Data and Model Poisoning'), ('output_handling', 'LLM05 - Improper Output Handling'), ('excessive_agency', 'LLM06 - Excessive Agency'), ('prompt_leakage', 'LLM07 - System Prompt Leakage'), ('vector_security', 'LLM08 - Vector and Embedding Security'), ('hallucination', 'LLM09 - Misinformation and Hallucination'), ('unbounded_consumption', 'LLM10 - Unbounded Consumption'), ('full_assessment', 'Full Security Assessment'), ('garak', 'Garak LLM Vulnerability Scan')], max_length=50),
        ),
    ]
