# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('claude', 'Claude'), ('huggingface', 'HuggingFace'), ('custom', 'Custom')], max_length=50)),
                ('model_family', models.CharField(blank=True, help_text='e.g., gpt-4, llama-3, claude-3', max_length=100)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('endpoint_url', models.URLField(blank=True, max_length=500)),
                ('api_key_ref', models.CharField(blank=True, help_text='Reference to encrypted API key', max_length=255)),
                ('context_window', models.IntegerField(default=4096, help_text='Max context window in tokens')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='e.g., ["chat", "completion", "embedding", "vision"]')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discovery_method', models.CharField(choices=[('manual', 'Manual'), ('auto_discovered', 'Auto Discovered'), ('api_scan', 'API Scan'), ('integration', 'Integration')], default='manual', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_models', to='projects.project')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'db_table': 'ai_assets_ai_model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('agent_type', models.CharField(choices=[('autonomous', 'Autonomous Agent'), ('assistant', 'Assistant'), ('workflow', 'Workflow Agent'), ('custom', 'Custom')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Agent permissions/scope')),
                ('tools', models.JSONField(blank=True, default=list, help_text='Available tools/plugins')),
                ('allowed_actions', models.JSONField(blank=True, default=list)),
                ('disallowed_actions', models.JSONField(blank=True, default=list)),
                ('human_approval_required', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('retired', 'Retired')], default='active', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_agents', to='projects.project')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='ai_assets.aimodel')),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'db_table': 'ai_assets_ai_agent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VectorDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('db_type', models.CharField(choices=[('pinecone', 'Pinecone'), ('weaviate', 'Weaviate'), ('qdrant', 'Qdrant'), ('chroma', 'Chroma'), ('pgvector', 'pgvector'), ('milvus', 'Milvus'), ('elasticsearch', 'Elasticsearch'), ('custom', 'Custom')], max_length=50)),
                ('endpoint_url', models.URLField(blank=True, max_length=500)),
                ('tenant_id', models.CharField(blank=True, help_text='Multi-tenant isolation ID', max_length=255)),
                ('dimension', models.IntegerField(default=1536, help_text='Vector dimension')),
                ('indexing_method', models.CharField(blank=True, max_length=100)),
                ('security_config', models.JSONField(blank=True, default=dict, help_text='Encryption, access controls')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_databases', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Vector Database',
                'verbose_name_plural': 'Vector Databases',
                'db_table': 'ai_assets_vector_database',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('chunking_strategy', models.CharField(choices=[('fixed', 'Fixed Size'), ('semantic', 'Semantic'), ('recursive', 'Recursive Character'), ('sentence', 'Sentence Split'), ('custom', 'Custom')], default='fixed', max_length=50)),
                ('chunk_size', models.IntegerField(default=1000)),
                ('chunk_overlap', models.IntegerField(default=200)),
                ('retrieval_config', models.JSONField(blank=True, default=dict, help_text='Top-K, similarity threshold, etc.')),
                ('security_config', models.JSONField(blank=True, default=dict, help_text='Access controls, isolation config')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_systems', to='ai_assets.aimodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_systems', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_systems', to='projects.project')),
                ('vector_db', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_systems', to='ai_assets.vectordatabase')),
            ],
            options={
                'verbose_name': 'RAG System',
                'verbose_name_plural': 'RAG Systems',
                'db_table': 'ai_assets_rag_system',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['organization', 'model_type'], name='ai_assets_a_organiz_57edd7_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['organization', 'is_active'], name='ai_assets_a_organiz_4c4506_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['model_family'], name='ai_assets_a_model_f_5eccce_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagent',
            index=models.Index(fields=['organization', 'status'], name='ai_assets_a_organiz_d34b49_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagent',
            index=models.Index(fields=['risk_level'], name='ai_assets_a_risk_le_486680_idx'),
        ),
        migrations.AddIndex(
            model_name='vectordatabase',
            index=models.Index(fields=['organization', 'db_type'], name='ai_assets_v_organiz_6e355c_idx'),
        ),
    ]
