# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assets', '0001_initial'),
        ('organizations', '__first__'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_rpm_limit', models.IntegerField(blank=True, help_text='Requests per minute limit', null=True)),
                ('current_tpm_limit', models.IntegerField(blank=True, help_text='Tokens per minute limit', null=True)),
                ('peak_rpm_observed', models.IntegerField(blank=True, null=True)),
                ('peak_tpm_observed', models.IntegerField(blank=True, null=True)),
                ('rate_limiting_active', models.BooleanField(default=False)),
                ('effectiveness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_limit_assessments', to='ai_assets.aimodel')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_assessments', to='scans.aiscan')),
            ],
            options={
                'verbose_name': 'Rate Limit Assessment',
                'verbose_name_plural': 'Rate Limit Assessments',
                'db_table': 'unbounded_consumption_rate_limit',
            },
        ),
        migrations.CreateModel(
            name='CostMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('avg_cost_per_request', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('budget_exceeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_monitors', to='ai_assets.aimodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_monitors', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Cost Monitor',
                'verbose_name_plural': 'Cost Monitors',
                'db_table': 'unbounded_consumption_cost_monitor',
                'unique_together': {('organization', 'model', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='DoSEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('token_exhaustion', 'Token Exhaustion'), ('rate_limit_breach', 'Rate Limit Breach'), ('concurrent_burst', 'Concurrent Request Burst'), ('cost_spike', 'Cost Spike'), ('resource_exhaustion', 'Resource Exhaustion'), ('api_abuse', 'API Abuse'), ('scraping', 'Scraping Detection')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('mitigated', 'Mitigated'), ('investigating', 'Investigating'), ('false_positive', 'False Positive'), ('resolved', 'Resolved')], default='detected', max_length=50)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Relevant metrics at time of event')),
                ('description', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dos_events', to='ai_assets.aimodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dos_events', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'DoS Event',
                'verbose_name_plural': 'DoS Events',
                'db_table': 'unbounded_consumption_dos_event',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['organization', 'severity'], name='unbounded_c_organiz_31c3dc_idx'), models.Index(fields=['status'], name='unbounded_c_status_b5184c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_type', models.CharField(choices=[('prompt', 'Prompt Tokens'), ('completion', 'Completion Tokens'), ('total', 'Total Tokens'), ('embedding', 'Embedding Tokens')], max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('requests_count', models.IntegerField(default=1)),
                ('avg_response_time_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('is_anomalous', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage', to='ai_assets.aiagent')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage', to='ai_assets.aimodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Token Usage Record',
                'verbose_name_plural': 'Token Usage Records',
                'db_table': 'unbounded_consumption_token_usage',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['organization', '-recorded_at'], name='unbounded_c_organiz_6dbfa3_idx'), models.Index(fields=['model'], name='unbounded_c_model_i_b88c4b_idx'), models.Index(fields=['is_anomalous'], name='unbounded_c_is_anom_c58ced_idx')],
            },
        ),
    ]
