# Generated by Django 6.0.6 on 2026-06-16 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_text', models.TextField()),
                ('is_malicious', models.BooleanField(default=False)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('injection_type', models.CharField(blank=True, choices=[('direct', 'Direct Prompt Injection'), ('indirect', 'Indirect Prompt Injection'), ('jailbreak', 'Jailbreak Attempt'), ('role_play', 'Role Play Attack'), ('context_leak', 'Context Leakage'), ('payload_splitting', 'Payload Splitting'), ('multi_language', 'Multi-Language Attack'), ('encoded', 'Encoded/obfuscated'), ('none', 'No Injection Detected')], max_length=50)),
                ('techniques_detected', models.JSONField(blank=True, default=list)),
                ('sanitized_prompt', models.TextField(blank=True)),
                ('detection_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prompt Scan',
                'verbose_name_plural': 'Prompt Scans',
                'db_table': 'prompt_injection_prompt_scan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptScanBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_prompts', models.IntegerField(default=0)),
                ('malicious_count', models.IntegerField(default=0)),
                ('avg_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prompt Scan Batch',
                'verbose_name_plural': 'Prompt Scan Batches',
                'db_table': 'prompt_injection_scan_batch',
            },
        ),
    ]
