# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assets', '0001_initial'),
        ('organizations', '__first__'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISBOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sbom_version', models.CharField(blank=True, max_length=50)),
                ('format', models.CharField(choices=[('cyclonedx', 'CycloneDX'), ('spdx', 'SPDX'), ('custom', 'Custom')], default='cyclonedx', max_length=50)),
                ('components', models.JSONField(blank=True, default=list, help_text='List of dependencies/components')),
                ('vulnerabilities', models.JSONField(blank=True, default=list, help_text='Known vulnerabilities')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sbom_data', models.JSONField(blank=True, default=dict, help_text='Full SBOM document')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sboms', to='ai_assets.aimodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sboms', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'AI SBOM',
                'verbose_name_plural': 'AI SBOMs',
                'db_table': 'supply_chain_ai_sbom',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SDKRiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sdk_name', models.CharField(max_length=255)),
                ('sdk_version', models.CharField(max_length=100)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('permissions_required', models.JSONField(blank=True, default=list)),
                ('data_access', models.JSONField(blank=True, default=list, help_text='Data the SDK can access')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('security_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdk_assessments', to='scans.aiscan')),
            ],
            options={
                'verbose_name': 'SDK Risk Assessment',
                'verbose_name_plural': 'SDK Risk Assessments',
                'db_table': 'supply_chain_sdk_risk',
            },
        ),
        migrations.CreateModel(
            name='DependencyScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_name', models.CharField(max_length=255)),
                ('dependency_version', models.CharField(max_length=100)),
                ('dependency_type', models.CharField(help_text='e.g., python-package, npm, docker-image', max_length=100)),
                ('known_vulnerabilities', models.JSONField(blank=True, default=list, help_text='CVE entries')),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=20)),
                ('latest_version', models.CharField(blank=True, max_length=100)),
                ('is_outdated', models.BooleanField(default=False)),
                ('license_info', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_scans', to='scans.aiscan')),
            ],
            options={
                'verbose_name': 'Dependency Scan',
                'verbose_name_plural': 'Dependency Scans',
                'db_table': 'supply_chain_dependency',
                'indexes': [models.Index(fields=['risk_level'], name='supply_chai_risk_le_f2ddb6_idx'), models.Index(fields=['dependency_name'], name='supply_chai_depende_e381c3_idx')],
            },
        ),
    ]
