# Generated by Django 6.0.6 on 2026-06-16 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_type', models.CharField(choices=[('api_key', 'API Key'), ('password', 'Password'), ('token', 'Access Token'), ('private_key', 'Private Key'), ('aws_key', 'AWS Key'), ('azure_key', 'Azure Key'), ('gcp_key', 'GCP Key'), ('database_url', 'Database URL'), ('connection_string', 'Connection String'), ('jwt_token', 'JWT Token'), ('oauth_token', 'OAuth Token'), ('encryption_key', 'Encryption Key')], max_length=50)),
                ('detected_value_hash', models.CharField(help_text='SHA-256 hash of detected secret', max_length=255)),
                ('source', models.CharField(choices=[('prompt', 'User Prompt'), ('model_output', 'Model Output'), ('training_data', 'Training Data'), ('system_prompt', 'System Prompt'), ('config', 'Configuration'), ('log', 'Log File')], max_length=50)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('context_snippet', models.TextField(blank=True, help_text='Surrounding context')),
                ('is_validated', models.BooleanField(default=False, help_text='Confirmed as valid secret')),
                ('severity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_scans', to='scans.aiscan')),
            ],
            options={
                'verbose_name': 'Secret Scan',
                'verbose_name_plural': 'Secret Scans',
                'db_table': 'sensitive_info_secret_scan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIIFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pii_type', models.CharField(choices=[('email', 'Email Address'), ('phone', 'Phone Number'), ('ssn', 'Social Security Number'), ('credit_card', 'Credit Card Number'), ('address', 'Physical Address'), ('dob', 'Date of Birth'), ('passport', 'Passport Number'), ('driver_license', "Driver's License"), ('bank_account', 'Bank Account'), ('ip_address', 'IP Address'), ('health_info', 'Health Information')], max_length=50)),
                ('count', models.IntegerField(default=1)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('context', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pii_findings', to='sensitive_info.secretscan')),
            ],
            options={
                'verbose_name': 'PII Finding',
                'verbose_name_plural': 'PII Findings',
                'db_table': 'sensitive_info_pii_finding',
            },
        ),
    ]
